# Generated by Django 4.2.5 on 2023-10-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100, verbose_name='Логин покупателя')),
                ('item', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('total', models.PositiveIntegerField(verbose_name='Сумма сделки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара, шт')),
                ('date', models.DateTimeField(verbose_name='Дата и время регистрации сделки')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
            },
        ),
    ]
