version: '3.3'

services:

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/server
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'